/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WantToSpeakRouteImport } from './routes/want-to-speak'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdviceRouteImport } from './routes/advice'
import { Route as IndexRouteImport } from './routes/index'

const WantToSpeakRoute = WantToSpeakRouteImport.update({
  id: '/want-to-speak',
  path: '/want-to-speak',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceRoute = AdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/contact': typeof ContactRoute
  '/travel': typeof TravelRoute
  '/want-to-speak': typeof WantToSpeakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/contact': typeof ContactRoute
  '/travel': typeof TravelRoute
  '/want-to-speak': typeof WantToSpeakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/contact': typeof ContactRoute
  '/travel': typeof TravelRoute
  '/want-to-speak': typeof WantToSpeakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advice' | '/contact' | '/travel' | '/want-to-speak'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advice' | '/contact' | '/travel' | '/want-to-speak'
  id: '__root__' | '/' | '/advice' | '/contact' | '/travel' | '/want-to-speak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdviceRoute: typeof AdviceRoute
  ContactRoute: typeof ContactRoute
  TravelRoute: typeof TravelRoute
  WantToSpeakRoute: typeof WantToSpeakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/want-to-speak': {
      id: '/want-to-speak'
      path: '/want-to-speak'
      fullPath: '/want-to-speak'
      preLoaderRoute: typeof WantToSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice': {
      id: '/advice'
      path: '/advice'
      fullPath: '/advice'
      preLoaderRoute: typeof AdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdviceRoute: AdviceRoute,
  ContactRoute: ContactRoute,
  TravelRoute: TravelRoute,
  WantToSpeakRoute: WantToSpeakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
